### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by mgiraldo** [nypl-spacetime/ideas#1]
- [ ] Build a consolidated 1850s manhattan/brooklyn dataset from the Building Inspector output
  - [x] Assemble latest B.I. output
  - [x] Manhattan 1857 centerlines
  - [ ] Brooklyn 1855 centerlines
- [ ] Integrate OldNYC data
  - [x] Raw OldNYC data
  - [ ] Clean OldNYC data (GeoJSON-ify)
- [ ] Integrate relevant PIC data

**Comment by riordan** [comment]
Other ideas:
- Parse pipeline for city directories
- generate key terminology gazetteer from Building Inspector Placenames + place lists in city directories
- mine NDNP newspapers for NYC for placenames
